// assets/src/components/Characters.vue
<template>
    <div class="game__characters">
      <h2>Characters</h2>
      <ul>
        <li
          :class="{active : characters.snake.sponge }"
          @click="toggleSnakeCharacter('sponge')"
        >Sponge</li>
        <li
          :class="{active : characters.snake.donaldJohnTrump}"
          @click="toggleSnakeCharacter('donaldJohnTrump')"
        >Donald Trump</li>
        <li
          :class="{active : characters.snake.fahrettinKoca}"
          @click="toggleSnakeCharacter('fahrettinKoca')"
        >Fahrettin Koca</li>
      </ul>
    </div>
</template>

<script>
export default {
  name: 'Characters',
  props: {
    characters : {
        type : Object,
        default: null
    }
  },
  data() {
      return {
        
      }
  },
  mounted(){
    this.$emit('characterChanged', this.characters)
  },
  methods:{
    toggleSnakeCharacter(character) {
        this.characters.snake.sponge = false;
        this.characters.snake.donaldJohnTrump = false;
        this.characters.snake.fahrettinKoca = false;
        if (character == "donaldJohnTrump") {
            this.characters.snake.donaldJohnTrump = !this.characters.snake.donaldJohnTrump;
        } else if (character == "fahrettinKoca") {
            this.characters.snake.fahrettinKoca = !this.characters.snake.fahrettinKoca;
        } else {
            this.characters.snake.sponge = !this.characters.snake.sponge;
        }

        this.$emit('characterChanged', this.characters)
    },
  }
}
</script>

<style lang="stylus">
  .game__characters {
    margin: 20px auto 0px;

    h2 {
      margin-top: 0;
      margin-bottom: 4px;
      font-size: 18px;
    }

    ul {
        list-style: none;
        display: flex;
        align-items: center;
        flex-wrap: wrap;

        li {
          margin-right: 10px;
          margin-bottom: 5px;
          font-size: 15px;
          cursor: pointer;
          opacity: 0.5;

        &.active {
          opacity: 1;
        }
      }
    }
  }
</style>

// src/components/Characters.tsx
import React from "react";
import styled from "styled-components";

type Characters = {
  snake: {
    // sponge: boolean;
    // fahrettinKoca: boolean;
    // donaldJohnTrump: boolean;
    [key: string]: boolean;
  };
};
type Props = {
  characters: Characters;
  onClick: (value: Characters) => void;
};

const StyledContainer = styled.div`
  margin: 20px auto 0px;

  ul {
    list-style: none;
    display: flex;
    align-items: center;
    flex-wrap: wrap;
  }
`;

const StyledTitle = styled.div`
  margin-top: 0;
  margin-bottom: 4px;
  font-size: 18px;
`;

const StyledCharacter = styled.li<{ selected: boolean }>`
  margin-right: 10px;
  margin-bottom: 5px;
  font-size: 15px;
  cursor: pointer;
  opacity: ${({ selected }) => (selected ? 1 : 0.5)};
`;

const data = [
  {
    name: "Donald Trump",
    value: "donaldJohnTrump",
  },
  {
    name: "Sponge",
    value: "sponge",
  },
  {
    name: "Fahrettin Koca",
    value: "fahrettinKoca",
  },
];

export const Characters = ({ characters, onClick }: Props) => {
  const toggleSnakeCharacter = (character: string) => {
    characters.snake.sponge = false;
    characters.snake.donaldJohnTrump = false;
    characters.snake.fahrettinKoca = false;

    if (character === "donaldJohnTrump") {
      characters.snake.donaldJohnTrump = !characters.snake.donaldJohnTrump;
    } else if (character === "fahrettinKoca") {
      characters.snake.fahrettinKoca = !characters.snake.fahrettinKoca;
    } else {
      characters.snake.sponge = !characters.snake.sponge;
    }

    onClick({ ...characters });
  };

  const selectedCharacter = Object.keys(characters.snake).find(
    (key) => characters.snake[key] === true
  );

  return (
    <StyledContainer>
      <StyledTitle>Characters</StyledTitle>
      <ul>
        {data.map(({ name, value }) => (
          <StyledCharacter
            selected={String(selectedCharacter) === value}
            key={value}
            onClick={() => toggleSnakeCharacter(value)}
          >
            {name}
          </StyledCharacter>
        ))}
      </ul>
    </StyledContainer>
  );
};
