// assets/src/components/VolumeButton.vue
<template>
  <button class="button--volume" title="Volume" @click="toggleVolume" v-if="!isMobile">
    <volume-2-icon v-if="sound.isMuted"></volume-2-icon>
    <volume-x-icon v-if="!sound.isMuted"></volume-x-icon>
  </button>
</template>

<script>
import isMobile from '../helpers/is-mobile'
import {
  Volume2Icon,
  VolumeXIcon
} from "vue-feather-icons";

export default {
  name: 'VolumeButton',
  components: {
    Volume2Icon,
    VolumeXIcon
  },
  props: {
    sound: {
      type: Object,
      default: null
    }
  },
  data() {
    return {
      isMobile: false
    }
  },
  created() {
    this.isMobile = isMobile()
  },
  methods: {
    toggleVolume() {
      this.sound.isMuted = !this.sound.isMuted;
      this.$emit('volumeChanged', this.sound);
    }
  }
}
</script>

// assets/src/components/VolumeButton.tsx
import React from "react";
import { Volume2Icon, VolumeXIcon } from "vue-feather-icons";
import { applyVueInReact } from "vuereact-combined";
// @ts-ignore
import isMobile from "../helpers/is-mobile.js";

const Volume2IconReact = applyVueInReact(Volume2Icon);
const VolumeXIconReact = applyVueInReact(VolumeXIcon);

type SoundProps = {
  isMuted: boolean;
};

type Props = {
  sound: SoundProps;
  onClick: (val: SoundProps) => void;
};

export const VolumeButton = ({ sound, onClick }: Props) => {
  const handleClick = () => {
    const updatedSound = { ...sound, isMuted: !sound.isMuted };
    onClick(updatedSound);
  };

  // @ts-ignore
  const mobile = isMobile();

  if (mobile) {
    return null;
  }

  return (
    <button className="button--volume" title="Volume" onClick={handleClick}>
      {sound.isMuted ? <Volume2IconReact /> : <VolumeXIconReact />}
    </button>
  );
};
