// assets/src/Snake.vue
<template>
  <section class="game" @keydown.esc="isModalVisible = false">
    <Header :score="snakeLength - 1" :bestScore="bestScore" :isScoreAnimationActive="scoreAnimation"
      :areScoresFetched="areScoresFetched" />

    <div class="game__area">
      <div class="game__area-overlay" :class="{ active: isModalVisible }">
        <button class="game__area-overlay-close" @click="isModalVisible = false" v-if="!isGameOver">
          <x-icon></x-icon>
        </button>
        <div class="game__area-overlay-content" v-html="this.modalTemplate"></div>
        <div v-if="!wantRestart">
          <button v-if="!isGameOver" @click="isModalVisible = false">OK</button>
          <button v-if="isGameOver" @click="gameOver">Try Again</button>
        </div>
        <button v-if="wantRestart" @click="gameOver">OK</button>
      </div>
      <ul>
        <li v-for="(item, colIndex) in gameLengthArray" :key="colIndex">
          <div v-for="(item, rowIndex) in gameLengthArray"
            :class="{ snake: bindSnake(colIndex, rowIndex), food: bindFood(colIndex, rowIndex), fahrettinKoca: characters.snake.fahrettinKoca, donaldJohnTrump: characters.snake.donaldJohnTrump }"
            :key="rowIndex"></div>
        </li>
      </ul>
    </div>

    <div class="game__footer">
      <button class="button--info" @click="toggleInfoModal">
        <info-icon></info-icon>
      </button>
      <button class="button--difficulty" @click="toggleDifficulty" :disabled="(snakeLength - 1) > 0">
        {{ this.gameDifficulties[this.gameDifficulty] }}
      </button>

      <VolumeButton :sound="sound" @click="(val) => sound = val" />
      <RestartButton @click="toggleRestartModal" :disabled="isModalVisible" />
    </div>

    <Characters :characters="characters" @characterChanged="characters = $event" />
  </section>
</template>

<script>
import { v4 as uuidv4 } from "uuid";
import {
  InfoIcon,
  XIcon,
} from "vue-feather-icons";
import db from "../firebaseInit.js";
import Characters from './components/Characters'
import { Header } from "./components/Header.tsx"
import { RestartButton } from "./components/RestartButton.tsx"
import { VolumeButton } from "./components/VolumeButton.tsx"
import { applyReactInVue } from 'vuereact-combined'

const MAX_SCORE = 100

export default {
  name: "Snake",
  components: {
    InfoIcon,
    XIcon,
    Characters,
    VolumeButton: applyReactInVue(VolumeButton),
    RestartButton: applyReactInVue(RestartButton),
    Header: applyReactInVue(Header),
  },
  data() {
    return {
      snake: [],
      snakeLength: 1,
      snakeDirection: "right",
      food: [{ x: 5, y: 7 }],
      gameSpeed: 100,
      gameLength: 20,
      gameAnimationTimer: null,
      isGameOver: false,
      gameDifficulties: ["easy", "medium", "hard"],
      gameDifficulty: 1,
      scoreAnimation: false,
      modalTemplate: "",
      isModalVisible: false,
      wantRestart: false,
      sound: {
        food: require("./assets/sound/food.mp3"),
        direction: require("./assets/sound/direction.mp3"),
        isMuted: false
      },
      bestScores: [],
      areScoresFetched: false,
      bestScore: {},
      characters: {
        snake: {
          sponge: true,
          fahrettinKoca: false,
          donaldJohnTrump: false
        }
      },
    };
  },

  computed: {
    gameLengthArray() {
      return Array.from({ length: this.gameLength }, (_, index) => index);
    }
  },

  created() {
    this.fetchScores(this.gameDifficulties[this.gameDifficulty]);
    this.init();
  },

  mounted() {
    window.addEventListener("keyup", this.bindSnakeDirections);
    // swipe actions
    const swipeGestures = new Hammer(document.querySelector(".game"));
    swipeGestures.get("swipe").set({ direction: Hammer.DIRECTION_ALL });

    swipeGestures.on("swipeleft", e => {
      if (this.snakeDirection == "right") return;
      this.snakeDirection = "left";
      this.playAudio(this.sound.direction, 0.05);
    });
    swipeGestures.on("swiperight", e => {
      if (this.snakeDirection == "left") return;
      this.snakeDirection = "right";
      this.playAudio(this.sound.direction, 0.05);
    });
    swipeGestures.on("swipeup", e => {
      if (this.snakeDirection == "down") return;
      this.snakeDirection = "up";
      this.playAudio(this.sound.direction, 0.05);
    });
    swipeGestures.on("swipedown", e => {
      if (this.snakeDirection == "up") return;
      this.snakeDirection = "down";
      this.playAudio(this.sound.direction, 0.05);
    });
  },

  watch: {
    snakeLength(newLen, oldLen) {
      if (newLen > oldLen) {
        this.scoreAnimation = true;
        setTimeout(() => (this.scoreAnimation = false), 400);
      }
    }
  },

  methods: {
    showBestScoreAlert() {
      var score = this.snakeLength - 1;
      this.$swal({
        allowOutsideClick: false,
        title: "🎉 Congrats! ",
        html: `<div class="swal2-html-container">You have made the best score. <br> Your score is ${that.snakeLength -
          1}. <br> You can save your name or leave it anonymous.</div><input id="bestScoreUserInput" class="swal2-input" value="anonymous" maxlength="40">`,
        preConfirm: () => {
          return new Promise((resolve) => {
            var input = document.getElementById("bestScoreUserInput");
            var scoreData = {
              user__id: uuidv4(),
              user__name: "anonymous",
              user__score: score
            };
            // set difficulty if not medium level
            if (this.gameDifficulty != 1) {
              scoreData.user__difficulty =
                this.gameDifficulties[that.gameDifficulty];
            }

            if (input.value.length > 1) {
              scoreData.user__name = input.value;
            } else {
              scoreData.user__name = "anonymous";
            }

            resolve(scoreData);
          });
        }
      })
        .then(data => {
          this.addNewHighScore(data.value);
        })
        .then(() => {
          this.init();
        });
    },
    fetchScores(difficulty) {
      var that = this;
      this.bestScores = [];
      this.areScoresFetched = false;
      this.bestScore = {};

      db.collection("scores")
        .get()
        .then(query => {
          query.forEach(item => {
            that.areScoresFetched = true;
            var scores = item.data();

            if (scores.user__difficulty !== undefined) {
              if (scores.user__difficulty === difficulty) {
                this.bestScores.push(scores);
              }
            } else {
              if (difficulty == "medium") {
                this.bestScores.push(scores);
              }
            }
          });

          this.bestScore = this.bestScores.reduce(function (prev, current) {
            return prev.user__score > current.user__score ? prev : current;
          });
        });
    },
    addNewHighScore(scoreData) {
      var that = this;

      db.collection("scores")
        .doc()
        .set(scoreData)
        .then(() => {
          this.fetchScores(that.gameDifficulties[that.gameDifficulty]);
        });
    },
    bindSnake(x, y) {
      for (let i = 0; i < this.snake.length; i++) {
        if (this.snake[i].x === x && this.snake[i].y === y) {
          return true;
        }
      }
    },
    bindFood(x, y) {
      for (var i in this.food) {
        if (this.food[i].x === x && this.food[i].y === y) {
          return true;
        }
      }
    },

    playAudio(audioSource, audioVolume) {
      if (this.sound.isMuted) return;
      var audio = new Audio(audioSource);
      audio.volume = audioVolume;
      audio.play();
    },

    animateSnake() {
      var snakeHead = this.snake[this.snake.length - 1];

      this.gameAnimationTimer = setInterval(() => {
        // right
        if (this.snakeDirection === "right") {
          snakeHead.x += 1;
        }
        // left
        else if (this.snakeDirection === "left") {
          snakeHead.x -= 1;
        }
        // up
        else if (this.snakeDirection === "up") {
          snakeHead.y -= 1;
        }
        // down
        else if (this.snakeDirection === "down") {
          snakeHead.y += 1;
        }

        // game area check
        if (snakeHead.x === this.gameLength) {
          snakeHead.x = 0;
        }
        if (snakeHead.x === -1) {
          snakeHead.x = this.gameLength - 1;
        }
        if (snakeHead.y === -1) {
          snakeHead.y = this.gameLength - 1;
        }
        if (snakeHead.y === this.gameLength) {
          snakeHead.y = 0;
        }

        this.preventSnakeToBiteItself(snakeHead);

        // length of snake
        this.snake.push({ x: snakeHead.x, y: snakeHead.y });
        if (this.snake.length > this.snakeLength) {
          this.snake.shift();
        }

        this.updatePoint();
      }, this.gameSpeed);
    },

    preventSnakeToBiteItself(head) {
      if (this.snakeLength < 2) {
        return;
      }
      for (let i = 0; i < this.snake.length; i++) {
        if (this.snake[i].x == head.x && this.snake[i].y == head.y) {
          this.toggleGameOverModal();
          // show best score alert
          var score = this.snakeLength - 1;
          if (score > this.bestScore.user__score) {
            this.showBestScoreAlert();
          }
        }
      }
    },

    updatePoint() {
      var snakeHead = this.snake[this.snake.length - 1];

      if (this.food[0].x === snakeHead.x && this.food[0].y === snakeHead.y) {
        this.snakeLength++;
        this.food = [];
        this.food.push(this.getRandomDirection());
        this.playAudio(this.sound.food, 0.1);

        // max score is reached
        if (this.snakeLength - 1 == MAX_SCORE) {
          clearInterval(this.gameAnimationTimer);
          this.$swal({
            allowOutsideClick: false,
            title: "🎉 Hooray!",
            text: "You have reached the maximum score!"
          }).then(() => {
            this.showBestScoreAlert();
          });
        }
      }
    },

    bindSnakeDirections(e) {
      e.preventDefault();

      let directions = {
        37: "left",
        38: "up",
        39: "right",
        40: "down"
      };
      // direction control check
      if (directions[e.keyCode] !== undefined) {
        if (
          (this.snakeDirection === "right" &&
            directions[e.keyCode] === "left") ||
          (this.snakeDirection === "left" &&
            directions[e.keyCode] === "right") ||
          (this.snakeDirection === "down" && directions[e.keyCode] === "up") ||
          (this.snakeDirection === "up" && directions[e.keyCode] === "down")
        ) {
          return false;
        }

        this.snakeDirection = directions[e.keyCode];
        this.playAudio(this.sound.direction, 0.05);
      }
    },
    getRandomDirection() {
      var maxPosition = this.gameLength;
      return {
        x: Math.floor(Math.random() * maxPosition),
        y: Math.floor(Math.random() * maxPosition)
      };
    },

    gameOver() {
      this.isGameOver = false;
      this.isModalVisible = !this.isModalVisible;
      this.wantRestart = false;
      this.init();
    },

    init() {
      clearInterval(this.gameAnimationTimer);
      this.snake = [];
      this.snakeLength = 1;
      this.snake.push(this.getRandomDirection());
      this.scoreAnimation = false;

      this.bindSnake();
      this.animateSnake();
    },
    toggleGameOverModal() {
      this.isGameOver = true;
      clearInterval(this.gameAnimationTimer);
      this.modalTemplate = `<p>😷<br />Game Over!<br />Your score is ${this
        .snakeLength - 1}.</p>`;
      this.isModalVisible = !this.isModalVisible;
    },
    toggleRestartModal() {
      this.modalTemplate = `<p>🧼<br> Restart?</p>`;
      this.isModalVisible = !this.isModalVisible;
      this.wantRestart = true;
    },
    toggleInfoModal() {
      this.modalTemplate = `<p>💡<br> Use your arrow buttons or swipe left, right, top or bottom to nagivate.</p>
        <br />
        <p>
          If your score is better than current best score, your score will be saved. You can save your name or leave it anonymous.
          <br />You can also see who has the best score by tapping on best score.
        </p>
        <p>Maximum score is 100. Have fun!</p>`;
      this.isModalVisible = !this.isModalVisible;
    },
    toggleDifficulty() {
      this.gameDifficulty++;
      if (this.gameDifficulty > 2) {
        this.gameDifficulty = 0;
      }

      var initSpeed = 100;
      if (this.gameDifficulty == 0) {
        this.gameSpeed = initSpeed + 20;
        this.init();
      } else if (this.gameDifficulty == 1) {
        this.gameSpeed = initSpeed;
        this.init();
      } else {
        this.gameSpeed = initSpeed - 20;
        this.init();
      }

      this.fetchScores(this.gameDifficulties[this.gameDifficulty]);
    }
  }
};
</script>

 
<style lang="stylus">
.game {
  margin: 0 auto;
  width: 400px;
  max-width: 100%;
}

@media screen and (max-width: 500px) {
  .game {
    width: 340px;
  }
}

// game area
.game__area {
  position: relative;
  margin: 10px 0;
  ovefflow: hidden;

  .game__area-overlay {
    position: absolute;
    background-color: rgba(32, 33, 44, 0.9);
    width: 100%;
    height: 100%;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    color: #fff;
    padding: 15px;
    text-align: center;
    visibility: hidden;
    opacity: 0;
    transition: all 0.1s linear;

    &.active {
      visibility: visible;
      opacity: 1;
    }

    .game__area-overlay-close {
      position: absolute;
      top: 10px;
      right: 10px;
      padding: 1px;
      background-color: transparent;
      display: flex;
      align-items: center;
      justify-content: center;
      opacity: 0.75;
    }

    .game__area-overlay-content {
      margin: 10px 0;
    }
  }

  ul {
    display: flex;

    li {
      list-style: none;
      min-width: 20px;
      min-height: 20px;
      border-right: 0;

      @media screen and (max-width: 500px) {
        min-width: 17px;
        min-height: 17px;
      }

      > div {
        background-color: #2d2f3d;
        width: 20px;
        height: 20px;

        @media screen and (max-width: 500px) {
          width: 17px;
          height: 17px;
        }

        &.snake {
          background-image: url('./assets/img/sponge.png');
          background-size: cover;

          &.donaldJohnTrump {
            background-image: url('./assets/img/donald-john-trump.png');
            background-size: 100% 100%;
          }

          &.fahrettinKoca {
            background-image: url('./assets/img/fahrettin-koca.png');
            background-size: 100% 100%;
          }
        }

        &.food {
          animation-name: scale;
          animation-duration: 0.4s;
          animation-timing-function: ease-in-out;
          background-image: url('./assets/img/virus.png');
          background-size: cover;
        }
      }
    }
  }
}

@keyframes scale {
  from {
    transform: scale(1);
  }

  to {
    transform: scale(1.4);
  }
}

// game footer
.game__footer {
  display: flex;
  justify-content: flex-end;

  button {
    svg {
      color: #fff;
      width: 22px;
      height: 22px;
    }

    &.button--info {
      margin-right: auto;
    }

    &.button--difficulty {
      margin-right: 10px;
      text-transform: capitalize;
    }

    &.button--volume {
      margin-right: 10px;
    }
  }
}
</style>

// src/Snake.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
import React, { useEffect, useState } from "react";
import styled from "styled-components";

import { Header } from "./components/Header";
import { DifficultyButton } from "./components/DifficultyButton";
import { InfoButton } from "./components/InfoButton";
import { RestartButton } from "./components/RestartButton";
import { VolumeButton } from "./components/VolumeButton";
import { Characters } from "./components/Characters";
import { Modal } from "./components/Modal";
import { useBestScores } from "./hooks/useBestScores";
import { useHighScore } from "./hooks/useHighScore";
// @ts-ignore
import foodSound from "../public/sound/food.mp3";
// @ts-ignore
import directionSound from "../public/sound/direction.mp3";

const StyledContainer = styled.div`
  margin: 0 auto;
  width: 400px;
  max-width: 100%;

  @media screen and (max-width: 500px) {
    width: 340px;
  }
`;

const StyledGameAreaContainer = styled.div`
  position: relative;
  margin: 10px 0;
  overflow: hidden;
`;

const StyledGameArea = styled.ul`
  display: flex;

  li {
    list-style: none;
    min-width: 20px;
    min-height: 20px;
    border-right: 0;

    @media screen and (max-width: 500px) {
      min-width: 17px;
      min-height: 17px;
    }

    > div {
      background-color: #2d2f3d;
      width: 20px;
      height: 20px;

      @media screen and (max-width: 500px) {
        width: 17px;
        height: 17px;
      }

      &.snake {
        background-image: url("./img/sponge.png");
        background-size: cover;

        &.donaldJohnTrump {
          background-image: url("./img/donald-john-trump.png");
          background-size: 100% 100%;
        }

        &.fahrettinKoca {
          background-image: url("./img/fahrettin-koca.png");
          background-size: 100% 100%;
        }
      }

      &.food {
        animation-name: scale;
        animation-duration: 0.4s;
        animation-timing-function: ease-in-out;
        background-image: url("./img/virus.png");
        background-size: cover;
      }
    }
  }
`;

const StyledGameFooter = styled.div`
  display: flex;
  justify-content: flex-end;
`;

const MAX_SCORE = 100;
const GAME_LENGTH = 20;

export type GameDifficulty = "easy" | "medium" | "hard";

type SnakeDirection = "left" | "right" | "up" | "down";

type Snake = {
  x: number;
  y: number;
};

const INITIAL_SNAKE_LENGTH = 1;
const INITIAL_SNAKE_DIRECTION: SnakeDirection = "right";

export const Snake = () => {
  const [snake, setSnake] = useState<Snake[]>([]);
  const [snakeLength, setSnakeLength] = useState(INITIAL_SNAKE_LENGTH);
  const [snakeDirection, setSnakeDirection] = useState<SnakeDirection>(
    INITIAL_SNAKE_DIRECTION
  );
  const [food, setFood] = useState([{ x: 5, y: 7 }]);
  const [gameSpeed, setGameSpeed] = useState(100);
  const [gameLength] = useState(GAME_LENGTH);
  const [isGameOver, setIsGameOver] = useState(false);
  const [gameDifficulties] = useState<GameDifficulty[]>([
    "easy",
    "medium",
    "hard",
  ]);
  const [gameDifficulty, setGameDifficulty] = useState(1);
  const [scoreAnimation, setScoreAnimation] = useState(false);
  const [modalTemplate, setModalTemplate] = useState("");
  const [isModalVisible, setIsModalVisible] = useState(false);
  const [wantRestart, setWantRestart] = useState(false);
  const [sound, setSound] = useState({
    food: new Audio(foodSound),
    direction: new Audio(directionSound),
    isMuted: false,
  });
  const [characters, setCharacters] = useState({
    snake: {
      sponge: true,
      fahrettinKoca: false,
      donaldJohnTrump: false,
    },
  });

  const { areScoresFetched, bestScore } = useBestScores(
    gameDifficulties[gameDifficulty]
  );
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { addNewHighScore } = useHighScore();

  useEffect(() => {
    init();

    return () => {
      window.removeEventListener("keyup", bindSnakeDirections);
    };
  }, [gameDifficulty]);

  const init = () => {
    setSnake([]);
    setSnakeLength(INITIAL_SNAKE_LENGTH);
    setSnake(() => [getRandomDirection()]);
    setScoreAnimation(false);
  };

  useEffect(() => {
    // @ts-ignore
    document.addEventListener("keydown", handleKeyPress);

    return () => {
      // @ts-ignore
      document.removeEventListener("keydown", handleKeyPress);
    };
  }, []);

  const moveSnake = () => {
    setSnake((prevSnake) => {
      const newSnake = [...prevSnake];
      const snakeHead = { ...newSnake[newSnake.length - 1] };

      if (snakeDirection === "right") {
        snakeHead.x += 1;
      } else if (snakeDirection === "left") {
        snakeHead.x -= 1;
      } else if (snakeDirection === "up") {
        snakeHead.y -= 1;
      } else if (snakeDirection === "down") {
        snakeHead.y += 1;
      }

      // game area check
      if (snakeHead.x === gameLength) {
        snakeHead.x = 0;
      } else if (snakeHead.x === -1) {
        snakeHead.x = gameLength - 1;
      } else if (snakeHead.y === -1) {
        snakeHead.y = gameLength - 1;
      } else if (snakeHead.y === gameLength) {
        snakeHead.y = 0;
      }

      preventSnakeToBiteItself(newSnake);

      newSnake.push(snakeHead);
      if (newSnake.length > snakeLength) {
        newSnake.shift();
      }

      return newSnake;
    });

    updatePoint();
  };

  const handleKeyPress = (event: React.KeyboardEvent<HTMLDivElement>) => {
    const validKeys = ["ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown"];
    const { key } = event;

    if (!validKeys.includes(key)) {
      return;
    }

    const direction = key.replace("Arrow", "").toLowerCase() as SnakeDirection;
    setSnakeDirection(direction);
    // @ts-ignore
    playAudio(sound.direction, 0.05);
  };

  useEffect(() => {
    if (!isGameOver) {
      const gameInterval = setInterval(moveSnake, gameSpeed);
      return () => clearInterval(gameInterval);
    }
  }, [moveSnake, gameSpeed, isGameOver]);

  const bindSnake = (x: number, y: number) => {
    for (let i = 0; i < snake.length; i++) {
      if (snake[i].x === x && snake[i].y === y) {
        return true;
      }
    }
  };

  const bindFood = (x: number, y: number) => {
    for (const item of food) {
      if (item.x === x && item.y === y) {
        return true;
      }
    }
  };

  const playAudio = (audioSource: string, audioVolume: number) => {
    if (sound.isMuted) return;
    const audio = new Audio(audioSource);
    audio.volume = audioVolume;
    audio.play();
  };

  const toggleRestartModal = () => {
    setModalTemplate(`<p>🧼<br> Restart?</p>`);
    setIsModalVisible(!isModalVisible);
    setWantRestart(true);
  };

  const toggleDifficulty = () => {
    setGameDifficulty((prevDifficulty) => {
      let newDifficulty = prevDifficulty + 1;
      if (newDifficulty > 2) {
        newDifficulty = 0;
      }

      const initSpeed = 100;
      if (newDifficulty === 0) {
        setGameSpeed(initSpeed + 20);
      } else if (newDifficulty === 1) {
        setGameSpeed(initSpeed);
      } else {
        setGameSpeed(initSpeed - 20);
      }

      //fetchScores(gameDifficulties[newDifficulty]);
      return newDifficulty;
    });
  };

  const preventSnakeToBiteItself = (snakeSegments: string | any[]) => {
    if (snakeSegments.length < 2) {
      return;
    }

    const snakeHead = snakeSegments[snakeSegments.length - 1];
    for (let i = 0; i < snakeSegments.length - 1; i++) {
      // Check if the snake's head collides with any other segment of the snake
      if (
        snakeHead.x === snakeSegments[i].x &&
        snakeHead.y === snakeSegments[i].y
      ) {
        toggleGameOverModal();
        const score = snakeSegments.length - 1;
        // @ts-ignore
        if (score > bestScore.user__score) {
          // showBestScoreAlert();
        }
        break;
      }
    }
  };

  const toggleGameOverModal = () => {
    setIsGameOver(true);

    setModalTemplate(
      `<p>😷<br />Game Over!<br />Your score is ${snakeLength - 1}.</p>`
    );
    setIsModalVisible(!isModalVisible);
  };

  const updatePoint = () => {
    const snakeHead = snake[snake.length - 1];

    if (food[0].x === snakeHead.x && food[0].y === snakeHead.y) {
      setSnakeLength((prevLength) => prevLength + 1);
      setFood([getRandomDirection()]);
      // @ts-ignore
      playAudio(sound.food, 0.1);

      // max score is reached
      if (snakeLength - 1 === MAX_SCORE) {
        /* Use the appropriate modal library here (e.g., React Modal or custom implementation) to show the alert. */
      }
    }
  };

  const bindSnakeDirections = (e: any) => {
    e.preventDefault();

    const directions: any = {
      37: "left",
      38: "up",
      39: "right",
      40: "down",
    };
    // direction control check
    if (directions[e.keyCode] !== undefined) {
      if (
        (snakeDirection === "right" && directions[e.keyCode] === "left") ||
        (snakeDirection === "left" && directions[e.keyCode] === "right") ||
        (snakeDirection === "down" && directions[e.keyCode] === "up") ||
        (snakeDirection === "up" && directions[e.keyCode] === "down")
      ) {
        return false;
      }

      setSnakeDirection(directions[e.keyCode]);
      // @ts-ignore
      playAudio(sound.direction, 0.05);
    }
  };

  const getRandomDirection = () => {
    const maxPosition = gameLength;
    return {
      x: Math.floor(Math.random() * maxPosition),
      y: Math.floor(Math.random() * maxPosition),
    };
  };

  const gameOver = () => {
    setIsGameOver(false);
    setIsModalVisible(!isModalVisible);
    setWantRestart(false);
    init();
  };

  return (
    <StyledContainer className="game">
      <Header
        score={snakeLength - 1}
        bestScore={bestScore}
        isScoreAnimationActive={scoreAnimation}
        areScoresFetched={areScoresFetched}
      />

      <StyledGameAreaContainer>
        <Modal
          isModalVisible={isModalVisible}
          setIsModalVisible={setIsModalVisible}
          modalTemplate={modalTemplate}
          wantRestart={wantRestart}
          isGameOver={isGameOver}
          gameOver={gameOver}
        />

        <StyledGameArea>
          {Array.from({ length: gameLength }).map((_, colIndex) => (
            <li key={colIndex}>
              {Array.from({ length: gameLength }).map((_, rowIndex) => (
                <div
                  key={rowIndex}
                  className={`${
                    bindSnake(colIndex, rowIndex)
                      ? "snake"
                      : bindFood(colIndex, rowIndex)
                      ? "food"
                      : ""
                  } ${
                    characters.snake.fahrettinKoca
                      ? "fahrettinKoca"
                      : characters.snake.donaldJohnTrump
                      ? "donaldJohnTrump"
                      : ""
                  }`}
                ></div>
              ))}
            </li>
          ))}
        </StyledGameArea>
      </StyledGameAreaContainer>

      <StyledGameFooter>
        <InfoButton
          onClick={(val) => {
            setModalTemplate(val);
            setIsModalVisible(!isModalVisible);
          }}
        />
        <DifficultyButton
          onClick={toggleDifficulty}
          disabled={snakeLength - 1 > 0}
        >
          {gameDifficulties[gameDifficulty]}
        </DifficultyButton>
        <VolumeButton sound={sound} onClick={(val) => setSound(val as any)} />
        <RestartButton onClick={toggleRestartModal} disabled={isModalVisible} />
      </StyledGameFooter>

      <Characters
        characters={characters}
        onClick={(val) => setCharacters(val as any)}
      />
    </StyledContainer>
  );
};
